spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



#    aliyun:
#      access-key: LTAI4GH9PkvF4d558TPiJwAz
#      secret-key:
#      oss:
#        endpoint: oss-cn-shanghai.aliyuncs.com
#        bucket: gulimall-futuresoldiers

  application:
    name: gulimall-third-party

server:
  port: 30000
alibaba:
  cloud:
    secret-key: 
    access-key: 
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com
      bucket: gulimall-futuresoldiers
    sms:
      host: 
      path: /dx/sendSms
      tpl_id: TP1711063
      appcode: 


