server:
  port: 40000
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.119.148


